backups:
  #
  # LVM --> Restic
  #
  - source:
      type: lvm
      vg_name: <VG_NAME>
      lv_name: <LV_NAME>
    destination:
      type: restic
      repo: <RESTIC_REPO>
  #
  # Directory --> Restic
  #
  - source:
      type: directory
      path: <DIRECTORY_PATH>
    destination:
      type: restic
      repo: <RESTIC_REPO>
